### PR TITLE
copy ngrok config to the right user account

### PR DESCRIPTION
**Pull request by johnorourke**
Hi there, I'm not sure if you accept pull requests but I discovered the ngrok.yml file is not being used, in these images because it's not copied into the ghostinspector user's home dir.

### CODE REVIEW

**Comment by aaronfay** [comment]
Hey @johnorourke, thanks for this, we'll get this rolled out as soon as we can! 👍🏻

**Review by aaronfay — APPROVED** [review]

**Comment by aaronfay** [comment]
@johnorourke the images should publish from our build system in a few minutes, can you try them out and confirm your issue is solved?

**Comment by johnorourke** [comment]
@aaronfay awesome, thank you!  Yes, will do.  Just as a by-the-way, the use-case for this is in a Bitbucket pipeline or Docker-compose environment, where we run test-runner-standalone as a service container, and need to contact the ngrok API from another container, so it needed to listen on all interfaces.

**Comment by johnorourke** [comment]
@aaronfay confirmed fixed in latest docker hub image.

**Pull request merged**
